BEGIN;

DROP TABLE IF EXISTS AccountStatements;
DROP TABLE IF EXISTS StockTransactions;
DROP TABLE IF EXISTS CompanyCapitalization;
DROP TABLE IF EXISTS Accounts;

COMMIT;

BEGIN;

DROP EXTENSION IF EXISTS "uuid-ossp";

COMMIT;