runtime: nodejs20
env: standard

automatic_scaling:
  target_cpu_utilization: 0.65

handlers:
  - url: /static
    static_dir: build/static

  - url: /(.*\.(json|ico|jpg|png|js))$
    static_files: build/\1
    upload: build/.*\.(json|ico|jpg|png|js)$

  - url: /.*
    static_files: build/index.html
    upload: build/index.html
